### PR TITLE
Resize favorite icon

### PR DESCRIPTION
**Pull request by objNameGit**
Resolves #

Added a star icon the same style as the edit icon

## Description

Favorite and editing icons had different styles, as a result, they were displayed in different ways.

## Proposed Changes
-

## Screenshots

image

## License

I confirm that this contribution is made under an MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by kevinhinterlong** [comment]
Let's change this

https://github.com/yahoo/navi/blob/dbcdc5638d71daa7de12bfa0af2046a973f43309/packages/dashboards/app/styles/navi-dashboards/components/navi-dashboard.less#L33-L35

 to be something like

```diff
   &__fav-icon {
     margin: 3px 10px;
+    .fa {
+      font-size: 18px;
+    }
   }
```

since we don't want to every `favorite-item` to be an `editable-label__icon`

**Comment by jkusa** [comment]
@objNameGit any update here?

**Comment by objNameGit** [comment]
> @objNameGit any update here?

i`m added fix.

**Comment by jkusa** [comment]
Thank you @objNameGit 🙏

**Pull request merged**
