### PR TITLE
Update app to 3.1

### PR DESCRIPTION
**Pull request by balajimanoharan**
Update app to 3.1

### CODE REVIEW

**Comment by Xuefeng-Zhu** [comment]
One this needs to be upgraded one version by one version?

**Comment by balajimanoharan** [comment]
> One this needs to be upgraded one version by one version?

Its the recommended way to upgrade. Also its easier to review that the update makes.

**Comment by Xuefeng-Zhu** [comment]
3.2 has been released

**Comment by balajimanoharan** [comment]
Closing this PR. Will reopen when its ready to review

**Pull request closed without merging**
